<?php
require __DIR__.'/bepusdt-bootstrap.php';
use lib\BepusdtClient as Client;
use lib\MerchantSubscription as Subscription;
use lib\GatewayHttp as Http;
foreach (['install','collection','bepusdt'] as $file) foreach(explode(';',file_get_contents(ROOT.'install/'.$file.'.sql')) as $sql) if(trim($sql)!=='') $DB->exec($sql);
foreach (['bepusdt_account','bepusdt_route','bepusdt_order','bepusdt_audit','subscription_purchase','subscription_event','collection_account','collection_route','collection_notify'] as $table) $DB->exec('DELETE FROM pre_'.$table);
$key=tempnam(sys_get_temp_dir(),'bepusdt-test-key-');file_put_contents($key,random_bytes(32));putenv('EPAY_COLLECTION_KEY_FILE='.$key);register_shutdown_function(fn()=>unlink($key));
$checks=0;
function check($value,$label){global $checks;if(!$value)throw new RuntimeException('FAIL: '.$label);$checks++;}
function reject(callable $fn,$label){try{$fn();}catch(Throwable $e){check(true,$label);return;}check(false,$label);}
function spawn(array $request){$p=proc_open([PHP_BINARY,ROOT.'tests/bepusdt-probe.php'],[['pipe','r'],['pipe','w'],['pipe','w']],$pipes);fwrite($pipes[0],json_encode($request));fclose($pipes[0]);return [$p,$pipes];}
function result($process){[$p,$pipes]=$process;$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($p)!==0)throw new RuntimeException('probe: '.$err);return $out;}
function probe($r){return json_decode(result(spawn($r)),true);}
foreach(['127.0.0.1','10.1.1.1','172.16.0.1','192.168.1.1','169.254.169.254','100.64.1.1','198.18.0.1','224.0.0.1','::1','fe80::1','::ffff:127.0.0.1','2001:db8::1','2002:7f00:1::','2001:0:123::'] as $ip)check(!Http::publicIp($ip),'private/reserved blocked '.$ip);
check(Http::publicIp('8.8.8.8')&&Http::publicIp('2606:4700:4700::1111'),'public IPv4 and IPv6');
foreach(['http://8.8.8.8/','https://u:p@example.com/','https://example.com/?x=1','https://example.com:8080/','https://example.com/../secret','https://example.com/%2e%2e/'] as $url)reject(fn()=>Http::endpoint($url),'unsafe endpoint');
reject(fn()=>Http::addresses('127.0.0.1'),'resolved private IP');
check(Http::endpoint('https://EXAMPLE.com/path')==='https://example.com/path/','canonical origin');
check(Client::decimal('0001.00',2)==='1','decimal normalization');foreach(['-1','1e2','0.001',null,[],true] as $n)reject(fn()=>Client::decimal($n,2),'invalid fiat');
$payload=['order_id'=>'123','amount'=>1.0,'status'=>0,'empty'=>''];$payload['signature']=Client::sign($payload,'test-token');check(Client::verify($payload,'test-token'),'sign numeric zero retained');check(!Client::verify($payload,'wrong-token'),'wrong token');$payload['signature']='';check(!Client::verify($payload,'test-token'),'empty signature');
// Golden signatures generated with Go fmt %v over JSON-decoded numbers, matching v1.24.2.
foreach ([[1,'fdfcb1e52b0efe09b1b699659571a184'],[1.1,'4088449c85e8b0c6e991d6b4659c1181'],[999999.99,'971d99efbf00dc8ac3799f7d3a7b4313'],[1000000,'5a3cd42f3d36d0a0447ea7ea12caff64'],[1000000.01,'ecfcbadca215f55a4f7afa352cebdb44'],[99999999.99,'8501ebf72c4e746f2d9e2266a9101393'],[0.00001,'0ee70b8f658ac7b4542a097acf7dc1ba']] as [$value,$hash]) check(Client::sign(['amount'=>$value,'status'=>2],'synthetic-token')===$hash,'Go numeric signature '.$value);
check(Subscription::addMonths('2028-01-31 15:20:00',1)==='2028-02-29 15:20:00','leap month clamp');check(Subscription::addMonths('2027-01-31 15:20:00',1)==='2027-02-28 15:20:00','regular month clamp');
$type=$DB->insert('type',['name'=>'usdt.trc20','showname'=>'USDT / TRC20','status'=>1]);
$parent=$DB->insert('channel',['mode'=>1,'type'=>$type,'plugin'=>'bepusdt','name'=>'Synthetic template','status'=>0,'rate'=>'100.00','costrate'=>'0.00','config'=>'{"bepusdt_managed":1}']);$conf['bepusdt_parent']=$parent;
$gid=$DB->insert('group',['name'=>'合成测试月费','isbuy'=>1,'price'=>'20.00','expire'=>1,'config'=>'{"bepusdt_enabled":1,"bepusdt_accounts":2}','info'=>'{}']);
$expiry=date('Y-m-d H:i:s',time()+86400*10);
foreach([1000,1001,1002] as $uid)$DB->insert('user',['uid'=>$uid,'gid'=>$uid===1002?0:$gid,'endtime'=>$uid===1002?null:$expiry,'key'=>'synthetic-key','money'=>'100.00','status'=>1,'pay'=>1,'msgconfig'=>serialize([])]);
$svc=new lib\BepusdtAccount($DB);$input=['endpoint'=>'https://8.8.8.8/','name'=>'合成网关','token'=>'synthetic-token','address'=>'T'.str_repeat('A',33),'timeout'=>'1200'];
$id=$svc->save(1000,$input,$parent);check($id>0,'save account');$account=$svc->owned(1000,$id);check($account['status']==0,'disabled until tested');check(!str_contains($account['secret'],'synthetic-token'),'encrypted token');check(!isset($svc->listing(1000)[0]['secret']),'no token in list');reject(fn()=>$svc->owned(1001,$id),'cross-owner read');reject(fn()=>lib\GatewaySecrets::decrypt($account['secret'],1001),'owner-bound ciphertext');reject(fn()=>$svc->action(1000,$id,'enable'),'unverified cannot enable');
$DB->update('bepusdt_account',['verified_at'=>'NOW()'],['id'=>$id]);reject(fn()=>$svc->action(1000,$id,'enable'),'probe is not payment test');
class FakeClient extends Client {
 public static $calls=0,$fail=false,$mutate=null;
 protected function post($path,array $params,$decode=true) {
  self::$calls++;if(self::$fail)throw new RuntimeException('synthetic transport failure');
  check(is_float($params['amount'])&&Client::verify($params,'synthetic-token'),'wire number and signature');
  $data=['order_id'=>$params['order_id'],'trade_id'=>'be-'.$params['order_id'],'fiat'=>'CNY','trade_type'=>$params['trade_type'],'amount'=>$params['amount'],'status'=>1,'token'=>$params['address']?:'T'.str_repeat('A',33),'actual_amount'=>'0.14','expiration_time'=>1200,'payment_url'=>'https://8.8.8.8/pay/'.$params['order_id']];
  if(self::$mutate)$data=(self::$mutate)($data);return ['status_code'=>200,'data'=>$data];
 }
}
class FakeGateway extends lib\BepusdtGateway {protected function client(array $c){return new FakeClient($c['appurl'],$c['appkey']);}}
$gateway=new FakeGateway($DB);
function makeOrder($id,$tid=0,$amount='1.00') {global $DB,$parent,$type;static $seq=0;$trade='2026100999'.str_pad((string)++$seq,9,'0',STR_PAD_LEFT);$DB->insert('order',['trade_no'=>$trade,'out_trade_no'=>'business-'.$trade,'uid'=>1000,'type'=>$type,'tid'=>$tid,'channel'=>$parent,'subchannel'=>$id,'name'=>'合成支付','money'=>$amount,'realmoney'=>$amount,'getmoney'=>$amount,'param'=>$tid===3?'{"bepusdt_test":1}':'','addtime'=>'NOW()','status'=>0,'notify_url'=>'https://example.invalid/notify','return_url'=>'https://example.invalid/return']);return $DB->find('order','*',['trade_no'=>$trade]);}
function receipt($o,$changes=[]){global $DB;$b=$DB->find('bepusdt_order','*',['trade_no'=>$o['trade_no']]);$data=array_merge(['order_id'=>$o['trade_no'],'trade_id'=>$b['provider_id'],'amount'=>1,'token'=>$b['address'],'actual_amount'=>'0.14','status'=>2,'block_transaction_id'=>'tx-'.$o['trade_no']],$changes);$data['signature']=Client::sign($data,'synthetic-token');return $data;}
$o=makeOrder($id,3);$channel=lib\Channel::getSub($id);$url=$gateway->create($o,$channel);check($url===$gateway->create($o,$channel)&&FakeClient::$calls===1,'create reused without upstream recreation');$gateway->notify($o['trade_no'],receipt($o));check($DB->findColumn('order','status',['trade_no'=>$o['trade_no']])==1,'test receipt paid');check(!empty($svc->owned(1000,$id)['tested_at']),'payment test unlocks account');
$svc->action(1000,$id,'enable');$svc->action(1000,$id,'default');$route=lib\Channel::getSubmitInfo($type,'usdt.trc20',1000,$gid,1);check($route['subchannel']==$id&&$route['rate']===100,'merchant route zero fee');check(isset(lib\Channel::getTypes(1000,$gid)[$type]),'type enumerated');
$GLOBALS['platform_payment']=true;check(lib\BepusdtAccount::route($DB,1000,$type,'usdt.trc20',1)===null,'subscription routes ignore merchant gateway');check(lib\CollectionAccount::route($DB,1000,1,'alipay',1,null)===null,'platform routes ignore merchant Alipay');unset($GLOBALS['platform_payment']);
$money=$DB->findColumn('user','money',['uid'=>1000]);$business=makeOrder($id);$gateway->create($business,$channel);
foreach([['amount'=>2],['actual_amount'=>0.15],['token'=>'T'.str_repeat('B',33)],['trade_id'=>'wrong'],['order_id'=>'other'],['status'=>'2'],['block_transaction_id'=>'']] as $change) reject(fn()=>$gateway->notify($business['trade_no'],receipt($business,$change)),'invalid receipt rejected');
check($DB->findColumn('order','status',['trade_no'=>$business['trade_no']])==0,'invalid receipt cannot settle');
$gateway->notify($business['trade_no'],receipt($business,['status'=>3]));check($DB->findColumn('bepusdt_order','state',['trade_no'=>$business['trade_no']])==='expired','timeout state');$gateway->notify($business['trade_no'],receipt($business));$gateway->notify($business['trade_no'],receipt($business));check($DB->findColumn('user','money',['uid'=>1000])===$money,'no principal credit or fee debit');check($DB->getColumn('SELECT COUNT(*) FROM pre_record WHERE trade_no=:t',[':t'=>$business['trade_no']])==0,'no per-order ledger charge');check($DB->getColumn('SELECT COUNT(*) FROM pre_collection_notify WHERE trade_no=:t',[':t'=>$business['trade_no']])==1,'one notification for repeated paid receipt');
reject(fn()=>$gateway->notify($business['trade_no'],receipt($business,['block_transaction_id'=>'different-chain-transaction'])),'conflicting replay');
$collision=makeOrder($id);$gateway->create($collision,$channel);reject(fn()=>$gateway->notify($collision['trade_no'],receipt($collision,['block_transaction_id'=>receipt($business)['block_transaction_id']])),'chain transfer cannot pay twice');check($DB->findColumn('order','status',['trade_no'=>$collision['trade_no']])==0,'receipt collision rolls back paid state');
$pending=makeOrder($id);$gateway->create($pending,$channel);$DB->update('user',['endtime'=>'2020-01-01 00:00:00'],['uid'=>1000]);check(lib\BepusdtAccount::route($DB,1000,$type,'usdt.trc20',1)===false,'expired route fails closed');reject(fn()=>$gateway->create(makeOrder($id),$channel),'expiry prevents new remote order');$gateway->notify($pending['trade_no'],receipt($pending));check($DB->findColumn('order','status',['trade_no'=>$pending['trade_no']])==1,'old callback survives expiry');$DB->update('user',['endtime'=>$expiry],['uid'=>1000]);
$rotated=makeOrder($id);$gateway->create($rotated,$channel);$svc->action(1000,$id,'disable');$svc->save(1000,array_merge($input,['id'=>$id,'token'=>'rotated-token']),$parent);$gateway->notify($rotated['trade_no'],receipt($rotated));check($DB->findColumn('order','status',['trade_no'=>$rotated['trade_no']])==1,'old token snapshot survives edit');check(!$svc->owned(1000,$id)['tested_at'],'old receipt cannot test new config');
// Restored synthetic credential allows remaining failure cases without provider access.
$svc->save(1000,array_merge($input,['id'=>$id]),$parent);$DB->update('bepusdt_account',['verified_at'=>'NOW()','tested_at'=>'NOW()'],['id'=>$id]);$svc->action(1000,$id,'enable');
$unknown=makeOrder($id);FakeClient::$fail=true;reject(fn()=>$gateway->create($unknown,$channel),'create timeout');$calls=FakeClient::$calls;FakeClient::$fail=false;reject(fn()=>$gateway->create($unknown,$channel),'unknown outcome never retried');check(FakeClient::$calls===$calls,'no duplicate gateway request');
foreach(['payment_url'=>'https://evil.example/pay','fiat'=>'USD','actual_amount'=>0,'amount'=>2,'token'=>'bad','status'=>2] as $field=>$value){FakeClient::$mutate=fn($d)=>array_merge($d,[$field=>$value]);reject(fn()=>$gateway->create(makeOrder($id),$channel),'malformed create '.$field);}FakeClient::$mutate=null;
reject(fn()=>$gateway->create(makeOrder($id,4),$channel),'merchant cannot collect platform subscription');reject(fn()=>$gateway->create(makeOrder($id,2),$channel),'merchant cannot top up platform balance');
$charged=makeOrder($id);$DB->update('order',['getmoney'=>'0.90'],['trade_no'=>$charged['trade_no']]);reject(fn()=>$gateway->create($charged,$channel),'fee drift rejected');
check(probe(['anonymous'=>true])['code']===-3,'API authentication');check(probe(['get'=>['act'=>'disable'],'post'=>['id'=>(string)$id]])['code']===-1,'API CSRF');check(probe(['method'=>'GET','get'=>['act'=>'disable'],'post'=>['id'=>(string)$id,'csrf'=>'synthetic-csrf']])['code']===-1,'API mutation method');check(probe(['uid'=>1001,'get'=>['act'=>'disable'],'post'=>['id'=>(string)$id,'csrf'=>'synthetic-csrf']])['code']===-1,'API ownership');foreach(['orders','notify','audit'] as $kind)check(probe(['uid'=>1001,'get'=>['act'=>'records','kind'=>$kind]])['data']===[],'record isolation '.$kind);
$api=probe(['pay_api'=>'fee-free-api']);check($api['code']==1,'signed payment API accepts subscription route');
$apiOrder=$DB->find('order','*',['out_trade_no'=>'fee-free-api']);check($apiOrder['money']==='1.00'&&$apiOrder['realmoney']==='1.00'&&$apiOrder['getmoney']==='1.00','actual API bypasses minimum fee and random addition');
$DB->update('user',['mode'=>1],['uid'=>1000]);probe(['pay_api'=>'fee-free-payer-mode']);$apiOrder=$DB->find('order','*',['out_trade_no'=>'fee-free-payer-mode']);check($apiOrder['realmoney']==='1.00'&&$apiOrder['getmoney']==='1.00','payer fee mode stays zero');
$parallel=makeOrder($id);$gateway->create($parallel,$channel);$n1=spawn(['notify'=>$parallel['trade_no'],'data'=>receipt($parallel)]);$n2=spawn(['notify'=>$parallel['trade_no'],'data'=>receipt($parallel)]);check(result($n1)==='1'&&result($n2)==='1','concurrent payment callback commits once');check($DB->getColumn('SELECT COUNT(*) FROM pre_collection_notify WHERE trade_no=:trade',[':trade'=>$parallel['trade_no']])==1,'concurrent callback emits one notification');
// Monthly billing: atomic balance purchase, idempotency and separate concurrent payments.
$before=$DB->find('user','*',['uid'=>1001]);$purchase=Subscription::purchase($DB,1001,$gid,1,0,'balance-one');check($purchase['code']===1,'balance purchase');Subscription::purchase($DB,1001,$gid,1,0,'balance-one');$after=$DB->find('user','*',['uid'=>1001]);check($after['money']==='80.00','duplicate purchase does not debit twice');check($after['endtime']===Subscription::addMonths($before['endtime'],1),'renew from existing expiry');
$platformChannel=$DB->insert('channel',['type'=>1,'name'=>'Synthetic platform','plugin'=>'alipay','mode'=>0,'status'=>1,'rate'=>'100.00']);
$r1=Subscription::purchase($DB,1001,$gid,1,1,'external-one');$r2=Subscription::purchase($DB,1001,$gid,1,1,'external-two');parse_str(parse_url($r1['url'],PHP_URL_QUERY),$q1);parse_str(parse_url($r2['url'],PHP_URL_QUERY),$q2);
$p1=spawn(['settle'=>$q1['trade_no']]);$p2=spawn(['settle'=>$q2['trade_no']]);check(result($p1)==='1'&&result($p2)==='1','concurrent renewal commits');check($DB->findColumn('user','endtime',['uid'=>1001])===Subscription::addMonths(Subscription::addMonths($after['endtime'],1),1),'concurrent months are cumulative');
$p1=spawn(['settle'=>$q1['trade_no']]);$p2=spawn(['settle'=>$q1['trade_no']]);check(result($p1)==='1'&&result($p2)==='1','duplicate concurrent callback');check($DB->getColumn('SELECT COUNT(*) FROM pre_subscription_event WHERE uid=1001')==3,'one entitlement per paid order');
reject(fn()=>Subscription::purchase($DB,1001,$gid,1,-1,'bad-type'),'negative payment type');reject(fn()=>Subscription::purchase($DB,1001,$gid,1,$type,'merchant-platform-type'),'merchant template excluded from monthly payment');
$DB->exec("CREATE TRIGGER bt_test_fail BEFORE INSERT ON pre_subscription_event FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic failure'");$before=$DB->find('user','*',['uid'=>1001]);reject(fn()=>Subscription::purchase($DB,1001,$gid,1,0,'rollback'),'event failure aborts balance transaction');$DB->exec('DROP TRIGGER bt_test_fail');check($DB->find('user','*',['uid'=>1001])===$before,'balance and expiry roll back');
$DB->update('user',['endtime'=>'2020-01-01 00:00:00'],['uid'=>1001]);Subscription::purchase($DB,1001,$gid,1,0,'expired');check(strtotime($DB->findColumn('user','endtime',['uid'=>1001]))>time()+27*86400,'late renewal starts now');
$r=Subscription::purchase($DB,1001,$gid,1,1,'review-change');parse_str(parse_url($r['url'],PHP_URL_QUERY),$review);
$otherGroup=$DB->insert('group',['name'=>'已切换套餐','config'=>'{}']);$DB->update('user',['gid'=>$otherGroup],['uid'=>1001]);
Subscription::settle($DB,$review['trade_no'],'synthetic-paid');check($DB->findColumn('subscription_event','state',['trade_no'=>$review['trade_no']])==='review','paid concurrent plan change enters review');check($DB->findColumn('user','gid',['uid'=>1001])==$otherGroup,'payment does not overwrite changed plan');
$second=$svc->save(1000,array_merge($input,['name'=>'第二个网关']),$parent);reject(fn()=>$svc->save(1000,$input,$parent),'saved account limit');
$DB->update('bepusdt_account',['verified_at'=>'NOW()','tested_at'=>'NOW()'],['id'=>$second]);$svc->action(1000,$second,'enable');
$DB->update('group',['config'=>'{"bepusdt_enabled":1,"bepusdt_accounts":1}'],['gid'=>$gid]);check(lib\BepusdtAccount::route($DB,1000,$type,'usdt.trc20',1)===false,'downgrade over-limit fails closed');$svc->action(1000,$second,'disable');check(is_array(lib\BepusdtAccount::route($DB,1000,$type,'usdt.trc20',1)),'selected account recovers after excess disabled');
$locked=makeOrder($id);$DB->update('group',['info'=>json_encode([$type=>['channel'=>0]])],['gid'=>$gid]);reject(fn()=>$gateway->create($locked,$channel),'uncreated cashier respects closed group type');$DB->update('group',['info'=>'{}'],['gid'=>$gid]);
$DB->update('type',['status'=>0],['id'=>$type]);reject(fn()=>$gateway->create($locked,$channel),'uncreated cashier respects disabled payment type');$DB->update('type',['status'=>1],['id'=>$type]);
$archive=makeOrder($id);$gateway->create($archive,$channel);$svc->action(1000,$id,'disable');$svc->action(1000,$id,'unroute');$svc->action(1000,$id,'archive');$gateway->notify($archive['trade_no'],receipt($archive));check($DB->findColumn('order','status',['trade_no'=>$archive['trade_no']])==1,'archived account receives old callback');
result(spawn(['setup'=>true]));$configured=$DB->getColumn("SELECT v FROM pre_config WHERE k='bepusdt_parent'");$template=$DB->find('channel','*',['id'=>$configured]);check($template['plugin']==='bepusdt'&&$template['status']==0&&$template['mode']==1,'CLI migration creates disabled direct template');
$count=$DB->getColumn('SELECT COUNT(*) FROM pre_channel');result(spawn(['setup'=>true]));check($DB->getColumn('SELECT COUNT(*) FROM pre_channel')==$count,'CLI migration idempotent');
require __DIR__.'/bepusdt-multichain.php';
echo "BEpusdt subscription: $checks checks passed\n";
